import * as React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ProductCard } from '@mikqi/product-card'
import { Button } from '@mikqi/button'
import clsx from 'clsx'
import { PRODUCTS_DATA } from '@/data/product'

const inter = Inter({
  variable: '--inter-font',
  subsets: ['latin'],
})

export default function Home() {
  const [scrollPosition, setScrollPosition] = React.useState(0)
  const listRef = React.useRef(null)

  const handleNextClick = () => {
    const container = document.getElementById('product-list-container')
    console.log(container)
    if (container) {
      container.scrollBy({
        left: 200,
        behavior: 'smooth',
      })
      setScrollPosition(container.scrollLeft + 200)
    }
  }

  const handlePrevClick = () => {
    const container = document.getElementById('product-list-container')
    if (container) {
      container.scrollBy({
        left: -200,
        behavior: 'smooth',
      })
      setScrollPosition(container.scrollLeft - 200)
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(inter.variable, 'max-w-7xl lg:mx-auto')}>
        <div className="py-16 sm:py-24 lg:mx-auto lg:max-w-7xl lg:px-8">
          <div className="relative mt-8">
            <div
              className="relative -mb-6 w-full overflow-x-auto pb-6"
              id="product-list-container"
              ref={listRef}
            >
              <div
                role="list"
                className="mx-2 lg:mx-4 inline-flex space-x-4 lg:space-x-8"
              >
                {PRODUCTS_DATA.map((product, idx) => (
                  <ProductCard
                    key={product.name}
                    name={product.name}
                    price={product.price}
                    discount={product.discount}
                    active={product.stock > 0}
                    src={`${product.image}?id=${idx}`}
                  />
                ))}
              </div>
            </div>

            <div className="absolute top-1/2 -left-10 transform -translate-y-1/2 flex">
              <Button
                className="px-4 py-2 bg-gray-200 hover:bg-gray-300 mr-4"
                onClick={handlePrevClick}
                disabled={scrollPosition <= 0}
              >
                Prev
              </Button>
            </div>
            <div className="absolute top-1/2 -right-10 transform -translate-y-1/2 flex">
              <Button
                className="px-4 py-2 bg-gray-200 hover:bg-gray-300"
                onClick={handleNextClick}
                disabled={
                  // @ts-expect-error
                  listRef.current?.scrollWidth -
                    // @ts-expect-error
                    listRef.current?.clientWidth -
                    50 <
                  Math.abs(scrollPosition)
                }
              >
                Next
              </Button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
