import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ProductCard } from '@mikqi/product-card'

const inter = Inter({
  variable: '--inter-font',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={inter.variable}
        style={{
          display: 'flex',
          width: '100%',
          gap: '4rem',
          padding: '2rem',
        }}
      >
        <ProductCard
          name="Adidas Pureboost 22 Running Shoes Sepatu Lari Pria"
          price={1695000}
          discount={50}
          src="/adidas.jpg"
        />
        <ProductCard
          name="Adidas Pureboost 22 Running Shoes Sepatu Lari Pria"
          price={1695000}
          src="/adidas.jpg"
          active={false}
        />
      </main>
    </>
  )
}
