import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ProductCard } from '@mikqi/product-card'
import clsx from 'clsx'
import { PRODUCTS_DATA } from '@/data/product'

const inter = Inter({
  variable: '--inter-font',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(inter.variable, 'max-w-7xl lg:mx-auto')}>
        <div className="py-16 sm:py-24 lg:mx-auto lg:max-w-7xl lg:px-8">
          <div className="relative mt-8">
            <div className="relative -mb-6 w-full overflow-x-auto pb-6">
              <div role="list" className="mx-4 inline-flex space-x-8">
                {PRODUCTS_DATA.map((product, idx) => (
                  <ProductCard
                    key={product.name}
                    name={product.name}
                    price={product.price}
                    discount={product.discount}
                    active={product.stock > 0}
                    src={`${product.image}?id=${idx}`}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
